In [1]:
import pandas as pd

In [10]:
dfb = pd.read_csv('Fashione-EAN-PLU.csv', dtype=str)
dfa = pd.read_csv("Fashione SKUs after deleting MP.csv", dtype=str)

In [11]:
before = dfb['PLU'].unique()
after = dfa['PLU'].unique()

In [12]:
deleted = list(set(before) - set(after))

In [13]:
dfb_temp = dfb[dfb['PLU'].isin(deleted)]
dfb_temp

,Brand,Style,Colour,Size,Description,PLU,EAN,SKU,Comm Code,Unnamed: 9
39496,MARTA PONTI,3120685,BLACK,NaN,briefcase,0002939000,NaN,NaN,NaN,NaN
39499,MARTA PONTI,3120815,BLACK,NaN,briefcase,0002939200,NaN,NaN,NaN,NaN
39501,MARTA PONTI,8105817,BLACK,NaN,handbag,0002939400,NaN,NaN,NaN,NaN
39502,MARTA PONTI,8105817,BLUE,NaN,handbag,0002939500,NaN,NaN,NaN,NaN
39503,MARTA PONTI,8105817,RED,NaN,handbag,0002939600,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
39656,MARTA PONTI,MP B225015,BLACK,NaN,wallet,0003934300,NaN,NaN,NaN,NaN
39657,MARTA PONTI,MP B225023,BLACK,NaN,wallet,0003933800,NaN,NaN,NaN,NaN
39658,MARTA PONTI,MP B225024,BLACK,NaN,wallet,0003934200,NaN,NaN,NaN,NaN
39659,MARTA PONTI,MP B225025,BLACK,NaN,wallet,0003933000,NaN,NaN,NaN,NaN
39660,MARTA PONTI,MP B225026,BLACK,NaN,key holder wallet,0003933700,NaN,NaN,NaN,NaN