In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df = pd.read_csv('unduplicated_orders.csv')
df['date'] = pd.to_datetime(df['date'])
df = df[(df['order_state'] == 'Order Dispatched') | (df['order_state'] == 'Order Refunded')]
df.drop_duplicates(inplace=True)

In [16]:
# df[df['customs_description'] == 'January Sale 2021']['title'].value_counts()

In [17]:
l = [[2, 2021], [3, 2021], [1, 2022], [2, 2022], [3, 2022], [1, 2023], [2, 2023], [3, 2023], [4, 2021], [5, 2021], [6, 2021], [4, 2022], [5, 2022], [6, 2022], [4, 2023], [5, 2023], [6, 2023], [7, 2021], [8, 2021], [9, 2021], [7, 2022], [8, 2022], [9, 2022], [7, 2023], [8, 2023], [9, 2023], [10, 2021], [11, 2021], [12, 2021], [10, 2022], [11, 2022], [12, 2022], [10, 2023], [11, 2023], [12, 2023]]
temp_df = df[(df['date'].dt.month == 1) & (df['date'].dt.year == 2021)].groupby('customs_description')['quantity'].sum().reset_index().sort_values(by='quantity', ascending=False).rename(columns={'quantity': f'1-2021'})
for i in l:
    temp_df = pd.merge(temp_df, df[(df['date'].dt.month == i[0]) & (df['date'].dt.year == i[1])].groupby('customs_description')['quantity'].sum().reset_index().rename(columns={'quantity': f'{i[0]}-{i[1]}'}), on='customs_description', how='outer')

temp_df.replace({np.NaN: 0}, inplace=True)

In [18]:
temp_df['Mean-Jan'] = temp_df[['1-2021', '1-2022', '1-2023']].mean(axis=1).round()
temp_df['Mean-Feb'] = temp_df[['2-2021', '2-2022', '2-2023']].mean(axis=1).round()
temp_df['Mean-Mar'] = temp_df[['3-2021', '3-2022', '3-2023']].mean(axis=1).round()

temp_df['Mean-Apr'] = temp_df[['4-2021', '4-2022', '4-2023']].mean(axis=1).round()
temp_df['Mean-May'] = temp_df[['5-2021', '5-2022', '5-2023']].mean(axis=1).round()
temp_df['Mean-Jun'] = temp_df[['6-2021', '6-2022', '6-2023']].mean(axis=1).round()

temp_df['Mean-Jul'] = temp_df[['7-2021', '7-2022', '7-2023']].mean(axis=1).round()
temp_df['Mean-Aug'] = temp_df[['8-2021', '8-2022', '8-2023']].mean(axis=1).round()
temp_df['Mean-Sep'] = temp_df[['9-2021', '9-2022', '9-2023']].mean(axis=1).round()

temp_df['Mean-Oct'] = temp_df[['10-2021', '10-2022', '10-2023']].mean(axis=1).round()
temp_df['Mean-Nov'] = temp_df[['11-2021', '11-2022', '11-2023']].mean(axis=1).round()
temp_df['Mean-Dec'] = temp_df[['12-2021', '12-2022', '12-2023']].mean(axis=1).round()

m = temp_df.select_dtypes(np.number)
temp_df[m.columns]= m.round().astype('Int64')

In [19]:
temp_df[:15].sort_values(by='Mean-Jan', ascending=False).reset_index(drop=True)[['customs_description', 'Mean-Jan', 'Mean-Feb', 'Mean-Mar', 'Mean-Apr', 'Mean-May', 'Mean-Jun',
                                                                                 'Mean-Jul', 'Mean-Aug', 'Mean-Sep', 'Mean-Oct', 'Mean-Nov', 'Mean-Dec']]

,customs_description,Mean-Jan,Mean-Feb,Mean-Mar,Mean-Apr,Mean-May,Mean-Jun,Mean-Jul,Mean-Aug,Mean-Sep,Mean-Oct,Mean-Nov,Mean-Dec
0,January Sale 2021,229,145,142,135,140,99,123,135,151,199,349,440
1,Ladies > Handbags,132,83,95,111,139,80,115,125,143,164,252,365
2,Mens > Accessories,111,85,62,51,49,59,57,70,74,123,272,419
3,Ladies > Ladies Jackets & Coats,106,83,87,79,66,28,41,48,102,145,202,221
4,Mens > Leather Jackets > Biker Styles,90,68,77,68,62,34,38,61,96,117,158,185
5,Ladies > Footwear,58,16,13,10,6,3,5,10,19,29,66,147
6,Ladies > Accessories > Gloves,48,26,9,6,3,1,1,3,8,22,68,184
7,Luggage > Holdall,48,27,30,36,40,40,47,58,67,71,131,174
8,Ladies > Purses,40,27,47,30,31,26,22,39,47,56,100,208
9,Mens > Man Bags & Briefcases > WashBags,17,16,11,12,13,17,15,23,23,32,87,127
10,Mens > Mens Jackets & Coats,15,5,5,4,1,1,2,1,7,12,22,19
11,Mens > Mens Waistcoats,14,11,12,12,18,5,9,13,10,25,27,32
12,Mens > Man Bags & Briefcases > Briefcases,13,12,11,8,10,9,12,18,12,19,25,42
13,Sheepskin & Fur > Sheepskin Hats,11,5,2,2,0,0,0,0,2,5,9,25
14,Mens > Leather Jackets > 3/4 Styles,5,2,2,1,1,0,1,0,4,4,10,8

In [20]:
temp_df[:15].sort_values(by='Mean-Jan', ascending=False).reset_index(drop=True)[['customs_description', 'Mean-Jan', 'Mean-Feb', 'Mean-Mar', 'Mean-Apr', 'Mean-May', 'Mean-Jun',
                                                                                 'Mean-Jul', 'Mean-Aug', 'Mean-Sep', 'Mean-Oct', 'Mean-Nov', 'Mean-Dec']]

,customs_description,Mean-Jan,Mean-Feb,Mean-Mar,Mean-Apr,Mean-May,Mean-Jun,Mean-Jul,Mean-Aug,Mean-Sep,Mean-Oct,Mean-Nov,Mean-Dec
0,January Sale 2021,229,145,142,135,140,99,123,135,151,199,349,440
1,Ladies > Handbags,132,83,95,111,139,80,115,125,143,164,252,365
2,Mens > Accessories,111,85,62,51,49,59,57,70,74,123,272,419
3,Ladies > Ladies Jackets & Coats,106,83,87,79,66,28,41,48,102,145,202,221
4,Mens > Leather Jackets > Biker Styles,90,68,77,68,62,34,38,61,96,117,158,185
5,Ladies > Footwear,58,16,13,10,6,3,5,10,19,29,66,147
6,Ladies > Accessories > Gloves,48,26,9,6,3,1,1,3,8,22,68,184
7,Luggage > Holdall,48,27,30,36,40,40,47,58,67,71,131,174
8,Ladies > Purses,40,27,47,30,31,26,22,39,47,56,100,208
9,Mens > Man Bags & Briefcases > WashBags,17,16,11,12,13,17,15,23,23,32,87,127
10,Mens > Mens Jackets & Coats,15,5,5,4,1,1,2,1,7,12,22,19
11,Mens > Mens Waistcoats,14,11,12,12,18,5,9,13,10,25,27,32
12,Mens > Man Bags & Briefcases > Briefcases,13,12,11,8,10,9,12,18,12,19,25,42
13,Sheepskin & Fur > Sheepskin Hats,11,5,2,2,0,0,0,0,2,5,9,25
14,Mens > Leather Jackets > 3/4 Styles,5,2,2,1,1,0,1,0,4,4,10,8